### ISSUE TITLE
What was the file encoding?

### ISSUE THREAD

**Issue by niotech** [David-Haim/CountriesToCitiesJSON#1]
I'm on python I can't get the encoding right with utf to byte code :(

**Comment by David-Haim-zz** [comment]
it should be utf8

**Comment by ThusStyles** [comment]
Theres weird characters sometimes, and there are some weird characters at the start of the file: ��{"China , also hundreds of the cities have weird characters like this - NgaoundÃ©rÃ©

**Comment by sentiasa** [comment]
Same issue for me even though I change the encoding to UTF-8. Maybe it's the github manipulating the characters

**Comment by rmpt** [comment]
for those who have problem with the encoding, this question had the solution for me (Java but can be used as base to other languages):
http://stackoverflow.com/questions/887148/how-to-determine-if-a-string-contains-invalid-encoded-characters

**Comment by David-Haim-zz** [comment]
Well, this JSON was pretty much neglected by me.
The characters issue is basically Windows' BOM. give me a few days to rearrange this JSON
